name: Build and Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to Hostinger Repo
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: build
          repository-name: z01tech-developers/hybits-clean-deploy
          token: ${{ secrets.DEPLOY_TOKEN }}
